#! /bin/bash

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if command -v include-what-you-use > /dev/null; then
  IWYU=include-what-you-use
elif command -v iwyu > /dev/null; then
  IWYU=iwyu
else
  echo "Can't find include-what-you-use or iwyu" 1>&2
  exit 1
fi

IWYU_ARGV=(
  -Xiwyu --mapping_file="$SCRIPT_ROOT/C18.txt"
  -Xiwyu --max_line_length=2048
)

"$IWYU" "${IWYU_ARGV[@]}" "$@"
retval=$?

[ $retval -eq 0 ] && exit 0
[ $retval -eq 1 ] && exit 1
[ $retval -eq 2 ] && exit 0
exit $retval
