#! /bin/bash

retrieve_latest_cmake() {
  local CMAKE_MINOR_VERSION="$1" _ revision file

  while IFS=$'\t' read -r _ revision; do
    revision="${revision#refs/tags/v}"
    [[ $revision = *-rc* ]] && continue
    wget -N --progress=dot:mega "https://github.com/Kitware/CMake/releases/download/v$revision/cmake-$revision-Linux-x86_64.tar.gz"
    case $? in
      0) break ;; 8) continue ;; *) return 1 ;;
    esac
  done < <(git ls-remote \
    --tags --refs \
    https://gitlab.kitware.com/cmake/cmake.git \
    "v$CMAKE_MINOR_VERSION.*" \
  | sort -t$'\t' -k2 -r --version-sort)

  file="cmake-$revision-Linux-x86_64.tar.gz"
  [ -e "$file" ] || return 1
  echo "Downloaded CMake $revision to $file" 1>&2
  mkdir -p .local
  tar -C .local -xzf "$file" --strip-components=1
}

cd ..

if [ ! -x .local/bin/cmake ]; then
  retrieve_latest_cmake 3.18
fi
if [ ! -e Makefile ]; then
  ./.local/bin/cmake . -DDOCUMENTATION=on -DDOXYGEN_GENERATE_HTML=no
fi
make doxygen
